# Test data

In [5]:
import numpy as np
import pandas as pd

class DummyProcessor:
    def __init__(self):
        self.pca_dim = 3

        # GENLINK-style format:
        # columns 0-5:
        # node_id1, node_id2, label_id1, label_id2, ibd_sum, ibd_n
        #
        # columns 6:6+pca_dim:
        # PCA coordinates for node_id1
        #
        # columns 6+pca_dim:6+2*pca_dim:
        # PCA coordinates for node_id2

        self.df = pd.DataFrame(
            [
                # edge: 0 -- 2
                [0, 2, "A", "B", 10.0, 1,  0.1, 0.2, 0.3,  2.1, 2.2, 2.3],

                # edge: 2 -- 1
                # node 2 appears again; same PCA as before, so drop_duplicates is safe
                [2, 1, "B", "A", 11.0, 2,  2.1, 2.2, 2.3,  1.1, 1.2, 1.3],

                # edge: 3 -- 0
                # node 0 appears again; same PCA as before, so drop_duplicates is safe
                [3, 0, "C", "A", 12.0, 3,  3.1, 3.2, 3.3,  0.1, 0.2, 0.3],
            ],
            columns=[
                "node_id1", "node_id2", "label_id1", "label_id2", "ibd_sum", "ibd_n",
                "node1_PC1", "node1_PC2", "node1_PC3",
                "node2_PC1", "node2_PC2", "node2_PC3",
            ],
        )

        # IMPORTANT:
        # This function assumes node IDs are already local integer IDs:
        # 0, 1, 2, ..., num_nodes - 1
        self.node_names_to_int_mapping = {
            0: 0,
            1: 1,
            2: 2,
            3: 3,
        }

    def make_node_pca_coords_from_edge_table(self):
        pca_dim = self.pca_dim
        num_nodes = len(self.node_names_to_int_mapping)

        node1_pca = pd.DataFrame(
            np.concatenate(
                [
                    self.df.iloc[:, [0]].to_numpy(),
                    self.df.iloc[:, 6:6 + pca_dim].to_numpy(dtype=np.float32),
                ],
                axis=1,
            )
        )
        node2_pca = pd.DataFrame(
            np.concatenate(
                [
                    self.df.iloc[:, [1]].to_numpy(),
                    self.df.iloc[:, 6 + pca_dim:6 + 2 * pca_dim].to_numpy(dtype=np.float32),
                ],
                axis=1,
            )
        )

        pca_columns = [f"pca_{i}" for i in range(pca_dim)]
        node1_pca.columns = ["node"] + pca_columns
        node2_pca.columns = ["node"] + pca_columns

        node_pca = pd.concat([node1_pca, node2_pca], axis=0, ignore_index=True)
        node_pca = node_pca.drop_duplicates(subset="node", keep="first")

        pca = np.zeros((num_nodes, pca_dim), dtype=np.float32)
        node_ids = node_pca["node"].to_numpy(dtype=np.int64)
        pca[node_ids] = node_pca.iloc[:, 1:].to_numpy(dtype=np.float32)

        return pca


processor = DummyProcessor()

print("Input edge table:")
display(processor.df)

pca = processor.make_node_pca_coords_from_edge_table()

print("\nResulting PCA matrix:")
print(pca)
print(pca[[3, 2, 1]])

expected = np.array(
    [
        [0.1, 0.2, 0.3],  # node 0
        [1.1, 1.2, 1.3],  # node 1
        [2.1, 2.2, 2.3],  # node 2
        [3.1, 3.2, 3.3],  # node 3
    ],
    dtype=np.float32,
)

print("\nExpected PCA matrix:")
print(expected)

print("\nMapping check:")
for node_id in range(expected.shape[0]):
    print(f"node {node_id}: got {pca[node_id].tolist()} | expected {expected[node_id].tolist()}")

assert np.allclose(pca, expected)

print("\nSUCCESS: PCA coordinates are mapped correctly by node ID.")

Input edge table:


,node_id1,node_id2,label_id1,label_id2,ibd_sum,ibd_n,node1_PC1,node1_PC2,node1_PC3,node2_PC1,node2_PC2,node2_PC3
0,0,2,A,B,10.0,1,0.1,0.2,0.3,2.1,2.2,2.3
1,2,1,B,A,11.0,2,2.1,2.2,2.3,1.1,1.2,1.3
2,3,0,C,A,12.0,3,3.1,3.2,3.3,0.1,0.2,0.3



Resulting PCA matrix:
[[0.1 0.2 0.3]
 [1.1 1.2 1.3]
 [2.1 2.2 2.3]
 [3.1 3.2 3.3]]
[[3.1 3.2 3.3]
 [2.1 2.2 2.3]
 [1.1 1.2 1.3]]

Expected PCA matrix:
[[0.1 0.2 0.3]
 [1.1 1.2 1.3]
 [2.1 2.2 2.3]
 [3.1 3.2 3.3]]

Mapping check:
node 0: got [0.10000000149011612, 0.20000000298023224, 0.30000001192092896] | expected [0.10000000149011612, 0.20000000298023224, 0.30000001192092896]
node 1: got [1.100000023841858, 1.2000000476837158, 1.2999999523162842] | expected [1.100000023841858, 1.2000000476837158, 1.2999999523162842]
node 2: got [2.0999999046325684, 2.200000047683716, 2.299999952316284] | expected [2.0999999046325684, 2.200000047683716, 2.299999952316284]
node 3: got [3.0999999046325684, 3.200000047683716, 3.299999952316284] | expected [3.0999999046325684, 3.200000047683716, 3.299999952316284]

SUCCESS: PCA coordinates are mapped correctly by node ID.


# Stats

In [5]:
import numpy as np
import pandas as pd


def calculate_dataset_stats(dataset):
    df = pd.read_csv(dataset) if isinstance(dataset, str) else dataset.copy()

    nodes = pd.concat([
        df[["node_id1", "label_id1"]].rename(columns={"node_id1": "node", "label_id1": "label"}),
        df[["node_id2", "label_id2"]].rename(columns={"node_id2": "node", "label_id2": "label"}),
    ], ignore_index=True).drop_duplicates("node")

    total_nodes = len(nodes)
    total_edges = len(df)

    pca_cols = [c for c in df.columns if c.startswith("node1_PC") or c.startswith("node2_PC")]
    has_pca = len(pca_cols) > 0

    rows = [
        ["total_edges", total_edges, np.nan],
        ["total_nodes", total_nodes, 1.0],
        ["labeled_nodes", int((nodes["label"] != "masked").sum()), int((nodes["label"] != "masked").sum()) / total_nodes if total_nodes else 0.0],
        ["masked_nodes", int((nodes["label"] == "masked").sum()), int((nodes["label"] == "masked").sum()) / total_nodes if total_nodes else 0.0],
        ["min_ibd_sum", float(df["ibd_sum"].min()) if total_edges else np.nan, np.nan],
        ["max_ibd_sum", float(df["ibd_sum"].max()) if total_edges else np.nan, np.nan],
        ["mean_ibd_sum", float(df["ibd_sum"].mean()) if total_edges else np.nan, np.nan],
        ["has_pca", has_pca, np.nan],
        ["num_pca_columns", len(pca_cols), np.nan],
    ]

    for label, count in nodes["label"].value_counts().items():
        rows.append([
            f"nodes_{label}",
            int(count),
            int(count) / total_nodes if total_nodes else 0.0,
        ])

    return pd.DataFrame(rows, columns=["metric", "value", "proportion"])

In [17]:
stats = calculate_dataset_stats("/disk/10tb/home/shmelev/New_CR_2025/OLD_CR_with_old_pca_labeled_only/with_pca/CR_real_masks_more_labeled_veritices_agreed_with_pca_features_with_actual_pca_coords.csv")
print(stats)

                     metric      value  proportion
0               total_edges      48602         NaN
1               total_nodes       3382    1.000000
2             labeled_nodes       3382    1.000000
3              masked_nodes          0    0.000000
4               min_ibd_sum    8.00004         NaN
5               max_ibd_sum    274.757         NaN
6              mean_ibd_sum  10.421886         NaN
7                   has_pca       True         NaN
8           num_pca_columns         40         NaN
9   nodes_Southern Russians       1289    0.381135
10   nodes_Northen Russians       1164    0.344175
11          nodes_Ukranians        477    0.141041
12        nodes_Belarusians        452    0.133649


# Metrics

In [1]:
import os
import json
import numpy as np
import pandas as pd


def graph_based_plus_and_one_hot_summary(
    data_path,
    dataset_dirs=None,
    selected_models=None,
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
):
    """
    Scans:

        data_path/
            dataset/
                model_feature_split/
                    results.json

    Keeps only folders that contain graph_based+ or one_hot.
    Summarizes metric by Dataset + Feature type + Model.
    """

    if not os.path.isdir(data_path):
        raise FileNotFoundError(f"Data path not found: {data_path}")

    if dataset_dirs is None:
        dataset_dirs = [
            d for d in os.listdir(data_path)
            if os.path.isdir(os.path.join(data_path, d))
        ]

    if isinstance(dataset_dirs, str):
        dataset_dirs = [dataset_dirs]

    if selected_models is not None and isinstance(selected_models, str):
        selected_models = [selected_models]

    all_rows = []
    raw_rows = []

    for dataset_dir in dataset_dirs:
        ds_path = os.path.join(data_path, dataset_dir)

        if not os.path.isdir(ds_path):
            print(f"Skipping missing dataset folder: {dataset_dir}")
            continue

        model_scores = {}

        for run_dir in os.listdir(ds_path):
            run_path = os.path.join(ds_path, run_dir)

            if not os.path.isdir(run_path):
                continue

            lname = run_dir.lower()

            feature_type = None
            for ft in feature_types:
                if ft.lower() in lname:
                    feature_type = ft
                    break

            if feature_type is None:
                continue

            results_path = os.path.join(run_path, "results.json")

            if not os.path.isfile(results_path):
                continue

            with open(results_path, "r") as f:
                res = json.load(f)

            model_name = res.get("model_name", run_dir)

            if selected_models is not None and model_name not in selected_models:
                continue

            if metric not in res:
                continue

            score = float(res[metric])

            key = (dataset_dir, feature_type, model_name)
            model_scores.setdefault(key, []).append(score)

            raw_rows.append(
                {
                    "Dataset": dataset_dir,
                    "Feature": feature_type,
                    "Model": model_name,
                    "Run folder": run_dir,
                    metric: score,
                    "results_path": results_path,
                }
            )

        if not model_scores:
            print(f"No selected feature runs found in dataset: {dataset_dir}")
            continue

        for (dataset_name, feature_type, model_name), scores in model_scores.items():
            if len(scores) != expected_runs:
                print(
                    f"Warning: dataset='{dataset_name}', "
                    f"feature='{feature_type}', "
                    f"model='{model_name}' expected {expected_runs} runs, "
                    f"found {len(scores)}"
                )

            all_rows.append(
                {
                    "Dataset": dataset_name,
                    "Feature": feature_type,
                    "Model": model_name,
                    "Mean": float(np.mean(scores)),
                    "Std": float(np.std(scores)),
                    "N": len(scores),
                    "Scores": scores,
                }
            )

    if not all_rows:
        raise RuntimeError(
            "No matching graph_based+ or one_hot runs found in the selected datasets."
        )

    summary_df = (
        pd.DataFrame(all_rows)
        .sort_values(["Dataset", "Feature", "Mean"], ascending=[True, True, False])
        .reset_index(drop=True)
    )

    raw_df = pd.DataFrame(raw_rows)

    return summary_df, raw_df

In [20]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_real_masks_more_labeled_veritices_agreed_with_pca_features"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_GNNM,0.594839,0.015024,10,"[0.5845844862026381, 0.5819350470374686, 0.584..."
1,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.587508,0.013149,10,"[0.5993362933128746, 0.5713679927976881, 0.574..."
2,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_GNNM,0.603646,0.016846,10,"[0.6245962182065676, 0.6150401472816719, 0.585..."
3,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.596670,0.016440,10,"[0.5911375475700293, 0.6005282340676438, 0.612..."


In [2]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_gt80_labeled_only_with_pca_min_edge_8p0_genlink_fixed",
        "CR_gt80_labeled_only_with_pca_min_edge_12p0_genlink_fixed",
        "CR_gt80_labeled_only_with_pca_min_edge_10p0_genlink_fixed"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.348738,0.024347,10,"[0.38182083314019066, 0.34403767476243213, 0.3..."
1,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,one_hot,GL_GNNM,0.348556,0.025380,10,"[0.34529190877813587, 0.37100335629747394, 0.4..."
2,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.313492,0.018602,10,"[0.30471362635540367, 0.33230457339609626, 0.3..."
3,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,one_hot,GL_GNNM,0.297872,0.015884,10,"[0.314153757977914, 0.2800973532096136, 0.2869..."
4,CR_gt80_labeled_only_with_pca_min_edge_8p0_gen...,one_hot,GL_GNNM,0.395779,0.033508,10,"[0.4352925730539069, 0.32986678579978473, 0.43..."
5,CR_gt80_labeled_only_with_pca_min_edge_8p0_gen...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.394385,0.024902,10,"[0.41721333986855386, 0.38695872981930934, 0.3..."


In [2]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_real_masks_more_labeled_veritices_agreed_with_pca_features_with_actual_pca_coords"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.590453,0.015229,10,"[0.5932952017830946, 0.5820115696940985, 0.565..."
1,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_GNNM,0.588372,0.013369,10,"[0.572783992116501, 0.580097004827251, 0.58038..."
2,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.602394,0.015713,10,"[0.6256501258229079, 0.6024878401291411, 0.616..."
3,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_GNNM,0.599790,0.018797,10,"[0.6118183453859194, 0.6253249033013947, 0.580..."


In [3]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_real_masks_more_labeled_veritices_agreed_with_pca_features"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_GNNM,0.594839,0.015024,10,"[0.5845844862026381, 0.5819350470374686, 0.584..."
1,CR_real_masks_more_labeled_veritices_agreed_wi...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.587508,0.013149,10,"[0.5993362933128746, 0.5713679927976881, 0.574..."
2,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_GNNM,0.603646,0.016846,10,"[0.6245962182065676, 0.6150401472816719, 0.585..."
3,CR_real_masks_more_labeled_veritices_agreed_wi...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.596670,0.016440,10,"[0.5911375475700293, 0.6005282340676438, 0.612..."


In [3]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CE_no_masks_3_same_class_ancestors_and_1_arbitrary_no_siblings_more_80_cr_copy"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.407465,0.030690,10,"[0.3986466860120384, 0.37940492256281727, 0.41..."
1,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_GNNM,0.388767,0.022970,10,"[0.39631885550537826, 0.433723083121032, 0.378..."
2,CE_no_masks_3_same_class_ancestors_and_1_arbit...,one_hot,GL_GNNM,0.419051,0.028098,10,"[0.38720020373599096, 0.4382645013129108, 0.44..."
3,CE_no_masks_3_same_class_ancestors_and_1_arbit...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.418354,0.023451,10,"[0.4347019706062259, 0.38447079236552917, 0.39..."


In [2]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_gt80_labeled_only_direct_labels"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_nw_k3_gnorm_leaky_relu,0.410897,0.026017,10,"[0.40920166716312756, 0.4643416584924168, 0.39..."
1,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_nw_k3_gnorm_relu,0.409378,0.030708,10,"[0.4450939612427183, 0.4161832165969222, 0.404..."
2,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_nw_k3_gnorm,0.405065,0.034437,10,"[0.3872338887316491, 0.4211200437581653, 0.407..."
3,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm_leaky_relu,0.404276,0.029365,10,"[0.3446519735048188, 0.40875865904892417, 0.40..."
4,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_nw_k3_gnorm_gelu,0.402276,0.028006,10,"[0.3905240303414917, 0.41016432774446365, 0.38..."
5,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.400199,0.031673,10,"[0.3579189013605637, 0.4115979573705538, 0.408..."
6,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm_relu,0.399605,0.025258,10,"[0.3950120869771048, 0.401932987010973, 0.3905..."
7,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm_gelu,0.396626,0.021819,10,"[0.4153529476996056, 0.3562616127833519, 0.386..."
8,CR_gt80_labeled_only_direct_labels,graph_based+,GL_SAGEConv_3l_512h,0.392515,0.025734,10,"[0.39057578860123837, 0.37484030900495796, 0.3..."
9,CR_gt80_labeled_only_direct_labels,graph_based+,GL_TAGConv_3l_512h_w_k3,0.388037,0.025137,10,"[0.3994278541809103, 0.38126078505417643, 0.41..."


In [3]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_new_no_masks_only_4_ancestors"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_new_no_masks_only_4_ancestors,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.445549,0.036243,10,"[0.502699639177705, 0.4550567292644757, 0.4484..."


In [2]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_gt80_labeled_only_with_pca_min_edge_8p0_genlink_fixed",
        "CR_gt80_labeled_only_with_pca_min_edge_12p0_genlink_fixed",
        "CR_gt80_labeled_only_with_pca_min_edge_10p0_genlink_fixed"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,graph_based+,GL_GNNM,0.332548,0.024813,10,"[0.31498713900254993, 0.3571595562132863, 0.31..."
1,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.325942,0.029715,10,"[0.3251128428415506, 0.37096870319289343, 0.31..."
2,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,one_hot,GL_GNNM,0.351950,0.026960,10,"[0.3075907239522242, 0.36895693414064595, 0.39..."
3,CR_gt80_labeled_only_with_pca_min_edge_10p0_ge...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.342861,0.023774,10,"[0.37377282085311286, 0.3296273054676416, 0.31..."
4,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.308520,0.016729,10,"[0.3148586030867584, 0.29229280275592745, 0.29..."
5,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,graph_based+,GL_GNNM,0.302635,0.019394,10,"[0.28257140287488464, 0.3123736864511214, 0.34..."
6,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.314384,0.022574,10,"[0.33939631967827927, 0.31815185308253013, 0.2..."
7,CR_gt80_labeled_only_with_pca_min_edge_12p0_ge...,one_hot,GL_GNNM,0.312964,0.026485,10,"[0.3271586345381526, 0.30516354501526, 0.33032..."
8,CR_gt80_labeled_only_with_pca_min_edge_8p0_gen...,graph_based+,GL_GNNM,0.393292,0.033256,10,"[0.42385924693506716, 0.3627371221281741, 0.39..."
9,CR_gt80_labeled_only_with_pca_min_edge_8p0_gen...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.389204,0.031838,10,"[0.33503113885169505, 0.39128729244355476, 0.3..."


In [11]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CR_gt80_labeled_only_with_pca_min_edge_8p0_genlink",
        "CR_gt80_labeled_only_no_pca_min_edge_12p0_genlink",
        "CR_gt80_labeled_only_no_pca_min_edge_10p0_genlink",
        "CR_gt80_labeled_only_with_pca_min_edge_12p0_genlink",
        "CR_gt80_labeled_only_no_pca_min_edge_8p0_genlink",
        "CR_gt80_labeled_only_with_pca_min_edge_10p0_genlink",
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CR_gt80_labeled_only_no_pca_min_edge_10p0_genlink,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.354623,0.021625,10,"[0.34634714573541675, 0.3326901482207304, 0.37..."
1,CR_gt80_labeled_only_no_pca_min_edge_10p0_genlink,graph_based+,GL_GNNM,0.349050,0.021492,10,"[0.3169903067262703, 0.3476017836397953, 0.351..."
2,CR_gt80_labeled_only_no_pca_min_edge_10p0_genlink,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.363617,0.032886,10,"[0.38220968672244365, 0.3682667426062596, 0.34..."
3,CR_gt80_labeled_only_no_pca_min_edge_10p0_genlink,one_hot,GL_GNNM,0.359367,0.033287,10,"[0.3126860619799907, 0.32555113082906706, 0.39..."
4,CR_gt80_labeled_only_no_pca_min_edge_12p0_genlink,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.337899,0.031393,10,"[0.3416199950665455, 0.31684506515231553, 0.29..."
5,CR_gt80_labeled_only_no_pca_min_edge_12p0_genlink,graph_based+,GL_GNNM,0.332496,0.029421,10,"[0.29074673637284076, 0.33909790254774413, 0.2..."
6,CR_gt80_labeled_only_no_pca_min_edge_12p0_genlink,one_hot,GL_GNNM,0.331745,0.022418,10,"[0.3526685647478562, 0.3288883360733755, 0.333..."
7,CR_gt80_labeled_only_no_pca_min_edge_12p0_genlink,one_hot,GL_TAGConv_3l_512h_w_k3_gnorm,0.330219,0.024927,10,"[0.3094760467726086, 0.31156493383997624, 0.31..."
8,CR_gt80_labeled_only_no_pca_min_edge_8p0_genlink,graph_based+,GL_GNNM,0.413296,0.030046,10,"[0.4758813491602286, 0.4089513431657475, 0.409..."
9,CR_gt80_labeled_only_no_pca_min_edge_8p0_genlink,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.400199,0.031673,10,"[0.3579189013605637, 0.4115979573705538, 0.408..."


In [12]:
summary_df, raw_df = graph_based_plus_and_one_hot_summary(
    data_path="/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/",
    dataset_dirs=[
        "CE_no_masks_3_same_class_ancestors_and_1_arbitrary_no_siblings_more_80_cr"
    ],
    feature_types=("graph_based+", "one_hot"),
    metric="f1_macro",
    expected_runs=10,
)

summary_df

,Dataset,Feature,Model,Mean,Std,N,Scores
0,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm_gelu,0.410036,0.028316,10,"[0.36884659252922725, 0.38571837768628253, 0.4..."
1,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm,0.407465,0.030690,10,"[0.3986466860120384, 0.37940492256281727, 0.41..."
2,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_512h_w_k3_gnorm_leaky_relu,0.383500,0.036781,2,"[0.42028120515244977, 0.3467184548243981]"
3,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_512h_w_k3,0.374789,0.020755,10,"[0.3735137607909914, 0.3929304246025252, 0.411..."
4,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_GINConv_3l_512h,0.374475,0.026508,10,"[0.37186543906054087, 0.34902196118488255, 0.4..."
5,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_GINConv_3l_128h,0.369832,0.019264,10,"[0.3567612448244259, 0.34729339465111825, 0.40..."
6,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_3l_128h_w_k3,0.322445,0.005702,10,"[0.32555541491875206, 0.3283616069505719, 0.32..."
7,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_9l_512h_w_k3,0.270286,0.005573,10,"[0.26881188118811883, 0.2629574635918308, 0.26..."
8,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_TAGConv_9l_128h_w_k3,0.252391,0.024312,10,"[0.2530602875806364, 0.2811996420380053, 0.237..."
9,CE_no_masks_3_same_class_ancestors_and_1_arbit...,graph_based+,GL_GATConv_3l_128h,0.245193,0.032088,10,"[0.21816869887646945, 0.24207124437647215, 0.2..."


In [2]:
df = graph_based_summary("/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/", "CR_gt80_labeled_only_with_pca_min_edge_8p0_genlink") # Western-Europe, CR, NC_graph_rel_eng, Scandinavia, Volga
df

,Model,Mean,Std
0,GL_TAGConv_3l_512h_w_k3_gnorm,0.409415,0.022486
1,GL_GNNM,0.398046,0.026066


In [3]:
# ---------- Example notebook cell ----------
data_root = "/disk/10tb/home/shmelev/GENLINK/downstream_tasks/runs/real_data_no_mask/"
summary_df = cr_graph_based_plus_summary(data_root)
summary_df


,Model,Mean,Std
0,GL_TAGConv_3l_512h_w_k3_gnorm,0.614577,0.016623
1,GL_TAGConv_3l_512h_nw_k3_gnorm_leaky_relu,0.612924,0.015017
2,GL_TAGConv_3l_512h_w_k3,0.612449,0.016688
3,GL_TAGConv_3l_512h_nw_k3_gnorm_relu,0.612396,0.013504
4,GL_TAGConv_3l_512h_w_k3_gnorm_leaky_relu,0.611929,0.018301
5,GL_TAGConv_3l_512h_w_k3_gnorm_relu,0.611912,0.015999
6,GL_MLP_9l_512h,0.610913,0.022341
7,GL_TAGConv_3l_512h_nw_k3_gnorm_gelu,0.610308,0.014395
8,GL_TAGConv_3l_512h_nw_k3_gnorm,0.610303,0.015755
9,GL_TAGConv_3l_512h_w_k3_gnorm_gelu,0.610284,0.017690


# GNN statistics

In [1]:
# JUPYTER CELL — analyze all torch geometric models in a .py file

import importlib.util
import inspect
import sys
import ast
import textwrap
from collections import Counter, defaultdict

import torch
import torch.nn as nn
import torch.nn.functional as F

import pandas as pd

# ---- torch_geometric basics
from torch_geometric.data import Data
from torch_geometric.nn.conv import MessagePassing  # most PyG convs derive from this

# ======================
# 1) CONFIG: your models file
# ======================
# 🔧 EDIT THIS to your actual file path (relative or absolute)
MODELS_FILE = "/disk/10tb/home/shmelev/GENLINK/utils/models.py"  # e.g., "models/gnn_zoo.py"

# ======================
# 2) Dynamic import
# ======================
spec = importlib.util.spec_from_file_location("user_models", MODELS_FILE)
module = importlib.util.module_from_spec(spec)
sys.modules["user_models"] = module
spec.loader.exec_module(module)

# ======================
# 3) Build a placeholder Data object
# ======================
def build_dummy_data(num_nodes=8, num_features=4, num_classes=4):
    # simple undirected ring graph with weights
    src = torch.arange(num_nodes)
    dst = (src + 1) % num_nodes
    edge_index = torch.stack([torch.cat([src, dst]), torch.cat([dst, src])], dim=0)

    x = torch.randn(num_nodes, num_features)
    edge_weight = torch.ones(edge_index.shape[1], dtype=torch.float)
    edge_attr = torch.ones(edge_index.shape[1], 1, dtype=torch.float)  # for convs that want edge_attr

    data = Data(x=x, edge_index=edge_index)
    data.weight = edge_weight           # some of your models use data.weight as edge weights
    data.edge_weight = edge_weight      # common PyG name
    data.edge_attr = edge_attr          # for NNConv/TransformerConv variants that expect edge features
    data.batch = torch.zeros(num_nodes, dtype=torch.long)  # for pooling ops if any

    # Some of your __init__ read these:
    data.num_classes = num_classes      # not a built-in Data property; we define it here
    # num_features is auto-derived from x.shape[-1] via Data.num_features property, so OK.

    return data

dummy_data = build_dummy_data(num_nodes=8, num_features=4, num_classes=4)

# ======================
# 4) Helpers
# ======================

# Which modules count as "learnable layers" (for depth)?
LEARNABLE_LAYER_TYPES = (nn.Linear, MessagePassing)

# Known activation module classes (nn.*)
_ACTIVATION_MODULE_NAMES = {
    "ReLU","ReLU6","LeakyReLU","ELU","SELU","CELU","GELU","SiLU","Swish",
    "Tanh","Sigmoid","Softplus","Softsign","Hardtanh","Hardsigmoid","Hardswish",
    "LogSoftmax","Softmax","PReLU","RReLU","Tanhshrink","Mish","Hardshrink"
}

def is_activation_module(m: nn.Module) -> bool:
    return type(m).__name__ in _ACTIVATION_MODULE_NAMES

# Extract activations used via torch.nn.functional.* / F.*
_ACTIVATION_F_NAMES = {
    "relu","relu6","leaky_relu","elu","selu","celu","gelu","silu",
    "tanh","sigmoid","softplus","softsign","hardtanh","hardsigmoid","hardswish",
    "log_softmax","softmax","prelu","rrelu","tanhshrink","mish","hardshrink"
}

def dotted_name_from_ast(node):
    """Reconstruct dotted name from an ast.Attribute/Name chain."""
    parts = []
    while isinstance(node, ast.Attribute):
        parts.append(node.attr)
        node = node.value
    if isinstance(node, ast.Name):
        parts.append(node.id)
    parts.reverse()
    return ".".join(parts)

def extract_functional_activations_from_forward(cls):
    acts = set()
    try:
        src = textwrap.dedent(inspect.getsource(cls.forward))
    except OSError:
        return acts  # source not available
    try:
        tree = ast.parse(src)
    except SyntaxError:
        return acts

    for node in ast.walk(tree):
        if isinstance(node, ast.Call):
            func = node.func
            if isinstance(func, ast.Attribute) or isinstance(func, ast.Name):
                dotted = dotted_name_from_ast(func)
                # We consider any call whose last piece is an activation name, and the prefix looks like F or functional
                last = dotted.split(".")[-1]
                prefix = ".".join(dotted.split(".")[:-1])
                if last.lower() in _ACTIVATION_F_NAMES and (
                    prefix in {"F", "torch.nn.functional", "nn.functional", "torch.nn.functional.functional"}
                    or prefix.endswith(".functional")
                    or dotted.startswith("F.")
                ):
                    acts.add(last.lower())
    return acts

def count_params(model: nn.Module):
    trainable = sum(p.numel() for p in model.parameters() if p.requires_grad)
    non_trainable = sum(p.numel() for p in model.parameters() if not p.requires_grad)
    return trainable, non_trainable

def run_with_hooks_and_capture_widths(model: nn.Module, data: Data, num_classes: int = 4):
    """
    Attach forward hooks to Linear and MessagePassing modules.
    Return (depth, widths_list) where widths_list are output feature sizes for each layer,
    and we will later derive a representative 'hidden width' from these.
    """
    widths = []
    handles = []

    def hook(_module, _inp, out):
        # out shape could be [N, C] (nodes), or a tuple for some layers. We try to get the feature size.
        # Prefer second dim if tensor; if tuple, grab first tensor-like element.
        t = out
        if isinstance(t, (tuple, list)):
            t = next((o for o in t if torch.is_tensor(o)), None)
        if torch.is_tensor(t):
            if t.dim() >= 2:
                widths.append(int(t.shape[-1]))
            elif t.dim() == 1:
                widths.append(int(t.shape[0]))  # fallback; unusual
        # else ignore

    for m in model.modules():
        if isinstance(m, LEARNABLE_LAYER_TYPES):
            handles.append(m.register_forward_hook(hook))

    model.eval()
    with torch.no_grad():
        try:
            _ = model(dummy_data)
        except Exception:
            # It's OK if forward fails for some model; we just won't have widths/depth for it.
            pass
    for h in handles:
        h.remove()

    # depth = how many learnable layers successfully produced an output
    depth = len(widths)

    # Compute a representative hidden width: consider widths that are neither input dim nor num_classes
    hidden_candidates = [w for w in widths if w != num_classes]
    # If everything equals num_classes (edge case), keep them anyway
    if not hidden_candidates:
        hidden_candidates = widths[:]
    # Pick the mode (most common). If tie, pick the max.
    if hidden_candidates:
        freq = Counter(hidden_candidates)
        max_count = max(freq.values())
        top = [w for w, c in freq.items() if c == max_count]
        rep_width = max(top)
    else:
        rep_width = None

    return depth, widths, rep_width

# ======================
# 5) Collect candidate classes
# ======================
all_classes = []
for name, obj in inspect.getmembers(module, inspect.isclass):
    # Only classes defined in this module (avoid imported PyTorch/PyG classes)
    if obj.__module__ == module.__name__ and issubclass(obj, nn.Module):
        all_classes.append((name, obj))

# ======================
# 6) Instantiate and analyze
# ======================
rows = []
errors = {}

for cls_name, cls in all_classes:
    info = {
        "model_name": cls_name,
        "depth": None,
        "width": None,
        "layer_widths_observed": None,
        "trainable_params": None,
        "non_trainable_params": None,
        "activations": None,
        "error": None,
    }
    try:
        # Attempt instantiation with the pattern you've shown: __init__(self, data)
        model = cls(dummy_data)
    except Exception as e:
        info["error"] = f"init: {type(e).__name__}: {e}"
        rows.append(info)
        errors[cls_name] = info["error"]
        continue

    # Count params
    tr, ntr = count_params(model)
    info["trainable_params"] = tr
    info["non_trainable_params"] = ntr

    # Depth + widths via forward hooks
    try:
        depth, widths, rep_width = run_with_hooks_and_capture_widths(model, dummy_data, num_classes=4)
        info["depth"] = depth
        info["width"] = rep_width
        info["layer_widths_observed"] = widths
    except Exception as e:
        info["error"] = f"hooks/forward: {type(e).__name__}: {e}"

    # Activations: both module-based and F.* functional calls
    acts_module = {type(m).__name__ for m in model.modules() if is_activation_module(m)}
    acts_f = extract_functional_activations_from_forward(cls)
    # Normalize names: module names already like 'ELU', function names are lower-case.
    acts_clean = set()
    acts_clean.update(acts_module)
    acts_clean.update(a.upper() for a in acts_f)
    info["activations"] = ", ".join(sorted(acts_clean)) if acts_clean else ""

    rows.append(info)

# ======================
# 7) Present results
# ======================
df = pd.DataFrame(rows)
# Order columns nicely
df = df[
    ["model_name", "depth", "width", "layer_widths_observed",
     "trainable_params", "non_trainable_params", "activations", "error"]
].sort_values("model_name").reset_index(drop=True)

# Pretty print
pd.set_option("display.max_colwidth", 200)
df


,model_name,depth,width,layer_widths_observed,trainable_params,non_trainable_params,activations,error
0,GL_ChebConv_3l_128h_w_k3,3.0,128.0,"[128, 128, 4]",52484.0,0.0,ELU,None
1,GL_GATConv_3l_128h,4.0,256.0,"[256, 256, 256, 4]",269060.0,0.0,ELU,None
2,GL_GATConv_3l_512h,4.0,1024.0,"[1024, 1024, 1024, 4]",4221956.0,0.0,ELU,None
3,GL_GATConv_9l_128h,10.0,256.0,"[256, 256, 256, 256, 256, 256, 256, 256, 256, 4]",1063172.0,0.0,ELU,None
4,GL_GATConv_9l_512h,10.0,1024.0,"[1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 1024, 4]",16835588.0,0.0,ELU,None
5,GL_GCNConv_3l_128h_nw,3.0,128.0,"[128, 128, 4]",17668.0,0.0,ELU,None
6,GL_GCNConv_3l_128h_w,3.0,128.0,"[128, 128, 4]",17668.0,0.0,ELU,None
7,GL_GCNConv_3l_32h_nw,3.0,32.0,"[32, 32, 4]",1348.0,0.0,ELU,None
8,GL_GCNConv_3l_512h_nw,3.0,512.0,"[512, 512, 4]",267268.0,0.0,ELU,None
9,GL_GCNConv_3l_512h_w,3.0,512.0,"[512, 512, 4]",267268.0,0.0,ELU,None


In [2]:
# Filter, format, and emit LaTeX (Booktabs) for your model stats DataFrame `df`

import pandas as pd
import math
import re

# --------- CONFIGURE caption/label if you like ---------
CAPTION = "Architecture statistics for selected widths (128/256/512/1024)."
LABEL = "tab:model_arch_stats"

# --------- Helper: LaTeX-escape cell contents ---------
_LATEX_SUBS = [
    ("\\", r"\textbackslash{}"),
    ("{", r"\{"),
    ("}", r"\}"),
    ("$", r"\$"),
    ("&", r"\&"),
    ("#", r"\#"),
    ("_", r"\_"),
    ("%", r"\%"),
    ("~", r"\textasciitilde{}"),
    ("^", r"\textasciicircum{}"),
]

def latex_escape(s):
    if s is None:
        return ""
    s = str(s)
    for a, b in _LATEX_SUBS:
        s = s.replace(a, b)
    # collapse excessive whitespace
    return re.sub(r"\s+", " ", s).strip()

# --------- 1) Filter by width ---------
keep_widths = {128, 256, 512, 1024}
df2 = df.copy()

# Ensure numeric width (coerce bad values to NaN, then filter)
df2["width"] = pd.to_numeric(df2["width"], errors="coerce")
df2 = df2[df2["width"].isin(keep_widths)].copy()

# --------- 2) Drop requested columns (if present) ---------
for col in ["error", "layer_widths_observed"]:
    if col in df2.columns:
        df2.drop(columns=col, inplace=True)

# --------- 3) Select & order columns for the table ---------
wanted_cols = ["model_name", "depth", "width", "trainable_params", "non_trainable_params", "activations"]
existing_cols = [c for c in wanted_cols if c in df2.columns]
df2 = df2[existing_cols]

# Sort for readability
sort_cols = [c for c in ["width", "depth", "model_name"] if c in df2.columns]
if sort_cols:
    df2 = df2.sort_values(sort_cols, kind="mergesort")

# --------- 4) Nicely format numbers ---------
def fmt_int(x):
    if x is None or (isinstance(x, float) and math.isnan(x)):
        return ""
    try:
        return f"{int(x):,}"
    except Exception:
        return str(x)

if "trainable_params" in df2.columns:
    df2["trainable_params"] = df2["trainable_params"].apply(fmt_int)
if "non_trainable_params" in df2.columns:
    df2["non_trainable_params"] = df2["non_trainable_params"].apply(fmt_int)

if "depth" in df2.columns:
    df2["depth"] = df2["depth"].apply(lambda v: "" if pd.isna(v) else f"{int(v)}")
if "width" in df2.columns:
    df2["width"] = df2["width"].apply(lambda v: "" if pd.isna(v) else f"{int(v)}")

# --------- 5) Build LaTeX (Booktabs) table ---------
# Column header names (pretty)
header_names = {
    "model_name": r"\textbf{Model}",
    "depth": r"\textbf{Depth}",
    "width": r"\textbf{Width}",
    "trainable_params": r"\textbf{Trainable}",
    "non_trainable_params": r"\textbf{Non-train}",
    "activations": r"\textbf{Activations}",
}
# Column alignment: l c c r r l
align_map = {
    "model_name": "l",
    "depth": "c",
    "width": "c",
    "trainable_params": "r",
    "non_trainable_params": "r",
    "activations": "l",
}
align_spec = "@{}" + "".join(align_map[c] for c in existing_cols) + "@{}"

# Header row
header_row = " & ".join(header_names[c] for c in existing_cols) + r" \\"

# Data rows
rows = []
for _, r in df2.iterrows():
    cells = []
    for c in existing_cols:
        cells.append(latex_escape(r[c]))
    rows.append(" & ".join(cells) + r" \\")
body_rows = "\n    ".join(rows) if rows else r"\multicolumn{6}{c}{\emph{No rows after filtering by width.}} \\"

latex_table = fr"""\begin{{table}}[h]
  \centering
  \caption{{{latex_escape(CAPTION)}}}
  \label{{{latex_escape(LABEL)}}}
  \begin{{tabular}}{{{align_spec}}}
    \toprule
    {header_row}
    \midrule
    {body_rows}
    \bottomrule
  \end{{tabular}}
\end{{table}}"""

print(latex_table)


\begin{table}[h]
  \centering
  \caption{Architecture statistics for selected widths (128/256/512/1024).}
  \label{tab:model\_arch\_stats}
  \begin{tabular}{@{}lccrrl@{}}
    \toprule
    \textbf{Model} & \textbf{Depth} & \textbf{Width} & \textbf{Trainable} & \textbf{Non-train} & \textbf{Activations} \\
    \midrule
    GL\_ChebConv\_3l\_128h\_w\_k3 & 3 & 128 & 52,484 & 0 & ELU \\
    GL\_GCNConv\_3l\_128h\_nw & 3 & 128 & 17,668 & 0 & ELU \\
    GL\_GCNConv\_3l\_128h\_w & 3 & 128 & 17,668 & 0 & ELU \\
    GL\_MLP\_3l\_128h & 3 & 128 & 17,668 & 0 & ELU \\
    GL\_SAGEConv\_3l\_128h & 3 & 128 & 35,076 & 0 & ELU \\
    GL\_SSGConv\_3l\_128h\_w\_a05\_k1 & 3 & 128 & 17,668 & 0 & ELU \\
    GL\_SSGConv\_3l\_128h\_w\_a09\_k1 & 3 & 128 & 17,668 & 0 & ELU \\
    GL\_TAGConv\_3l\_128h\_nw\_k3 & 3 & 128 & 69,892 & 0 & ELU \\
    GL\_TAGConv\_3l\_128h\_w\_k3 & 3 & 128 & 69,892 & 0 & ELU \\
    GL\_GCNConv\_9l\_128h\_nw & 9 & 128 & 116,740 & 0 & ELU \\
    GL\_GCNConv\_9l\_128h\_w & 9 & 128 & 116,7